import { FullLanguage } from "./types";

export const pl = {
  noUser: "Nie ma takiego użytkownika",
  badPassword: "Hasło jest niepoprawne",
  userExists: "Taki użytkownik już istnieje",
  badEmail: "E-mail ma niepoprawny format",
  emailPlaceholder: "E-mail",
  passwordPlaceholder: "Hasło",
  confirmPasswordPlaceholder: "Powtórz hasło",
  somethingWrong: "Coś jest nie tak, spróbuj ponownie później",
  logIn: "Zaloguj się",
  logInBenefit: "Aby zdobyć więcej haseł i zapisać je w swojej kolekcji",
  logInButton: "Zaloguj",
  orUse: "lub użyj",
  logInWithFacebook: "Zaloguj się z Facebookiem",
  noAccount: "Nie masz konta?",
  signUp: "Zarejestruj się",
  haveAccount: "Masz już konto?",
  signIn: "Zaloguj się",
  agreeWith: "Akceptuję",
  privacyPolicy: "politykę prywatności",
  forgotPassword: "Przypomnij hasło",
  forgotPasswordDisclaimer: "Wprowadź e-mail do Twojego konta",
  emailHasBeenSended: "Wiadomość została wysłana na podany adres email",
  loggedInWithServices: "Konto o podanym e-emailu loguje się z innego źródła",
  send: "Wyślij",
  helloUser: "Cześć {{user}}!",
  changeLanguage: "Język",
  logOut: "Wyloguj się",
  newGame: "Nowa gra",
  resumeGame: "Wznów grę",
  categories: "Kategorie",
  showBought: "pokaż kupione",
  buyCategory: "Kup kategorię",
  randomWord: "Losuj hasło",
  youHaveNewWords: "Masz nowe hasła!",
  saveCategory: "Zapisz kategorię",
  super: "Super",
  getWords: "Zyskaj hasła",
  howToPlay: "Jak grać?",
  howToPlay1: "Zbierz grupę znajomych, skonfiguruj rozgrywkę i bawcie się!",
  howToPlay2: "Pokazujcie wylosowane hasła i nic nie mówcie",
  howToPlay3:
    "Jeśli zabraknie haseł, możesz je zdobyć i zwiększać swoją kolekcję!",
  reset: "reset",
  teamsAmount: "Ilość drużyn",
  players: "Gracze",
  roundTime: "Długość rundy",
  whenWin: "Do ilu punktów",
  countType: "Tryb",
  rollTeams: "Losuj drużyny",
  rollTeamsAgain: "Losuj jeszcze raz",
  startGame: "Zacznij grę",
  startNewGame: "Zacznij nową grę",
  numberOfWords: "Ilość wybranych haseł",
  roll: "Losuj",
  free: "darmowe",
  randomFreeWords: "Darmowe hasła",
  dontKnowWords: "Lepiej będzie jeśli nie będziesz znać słów.",
  wantToSee: "Chcę zobaczyć",
  thanks: "Dzięki",
  gameSettings: "Ustawienia gry",
  onePerRound: "Punkt na rundę",
  asManyPerRound: "Tyle ile możliwe",
  nameOrNick: "Imię lub nazwa",
  clearHistory: "wyczyść historę",
  selectCategories: "Wybierz kategorie",
  selectedWords: "Wybrane hasła",
  letsPlay: "Zagrajmy!",
  red: "Drużyna czerwona",
  green: "Drużyna zielona",
  orange: "Drużyna pomarańczowa",
  blue: "Drużyna niebieska",
  violet: "Drużyna fioletowa",
  yellow: "Drużyna żółta",
  round: "Runda:",
  category: "Kategoria:",
  replaceWordOnce: "Jednokrotna zmiana hasła",
  correct: "Dobrze",
  winner: "Wygrywa",
  winners: "Wygrywają",
  words: "Słowa:",
  seeAd: "Zobacz reklamę",
  getNewWords: "Zdobądź {{words}} nowych haseł",
  yes: "Tak",
  cancel: "Zamknij",
  adLoadingError: "Błąd w ładowaniu reklamy, spróbuj później",
  claimReward: "Odbierz nagrodę",
  congratulations: "Gratulacje",
};

export const en = {
  noUser: "Could not find user",
  badPassword: "Password is wrong",
  userExists: "This user already exists",
  badEmail: "E-mail is not valid",
  emailPlaceholder: "E-mail",
  passwordPlaceholder: "Password",
  confirmPasswordPlaceholder: "Confirm password",
  somethingWrong: "Something is wrong, please try again later",
  logIn: "Login",
  logInBenefit: "To get more words and save them in Your collection",
  logInButton: "Sign in",
  orUse: "or use",
  logInWithFacebook: "Log in with Facebook",
  noAccount: "Don't have an account?",
  signUp: "Sign up",
  haveAccount: "Already have an account?",
  signIn: "Sign in",
  agreeWith: "I agree with",
  privacyPolicy: "privacy policy",
  forgotPassword: "Forgot password?",
  forgotPasswordDisclaimer: "Provide e-mail for Your account",
  emailHasBeenSended: "Message has been sended to given e-mail address",
  loggedInWithServices: "Account with given e-mail logs from different source",
  send: "Send",
  helloUser: "Hi {{user}}!",
  changeLanguage: "Language",
  logOut: "Log out",
  newGame: "New game",
  resumeGame: "Resume game",
  categories: "Categories",
  showBought: "show bought",
  buyCategory: "Buy Category",
  randomWord: "Random word",
  youHaveNewWords: "You have new words!",
  saveCategory: "Save category",
  super: "Super",
  getWords: "Get new words",
  howToPlay: "How to play?",
  howToPlay1: "Gather a group of friends, set up the game and have fun!",
  howToPlay2: "Show drawn word and say nothing",
  howToPlay3:
    "If You run out of words, You can get new ones and increase Your collection!",
  reset: "reset",
  teamsAmount: "Number of teams",
  players: "Players",
  roundTime: "Round time",
  whenWin: "Points",
  countType: "Type",
  rollTeams: "Random players",
  rollTeamsAgain: "Random again",
  startGame: "Start game",
  startNewGame: "Start new game",
  numberOfWords: "Amount of choosen words",
  roll: "Roll",
  free: "free",
  randomFreeWords: "Free words",
  dontKnowWords: "It will be better if You don't know the words.",
  wantToSee: "I want to see",
  thanks: "Thanks",
  gameSettings: "Game settings",
  onePerRound: "Point per round",
  asManyPerRound: "As many as possible",
  nameOrNick: "Name or nick",
  clearHistory: "clear history",
  selectCategories: "Select categories",
  selectedWords: "Selected words",
  letsPlay: "Let's play the game!",
  red: "Red team",
  green: "Green team",
  orange: "Orange team",
  blue: "Blue team",
  violet: "Violet team",
  yellow: "Yellow team",
  round: "Round:",
  category: "Category:",
  replaceWordOnce: "Replace the word once",
  correct: "Correct",
  winner: "Winner",
  winners: "Winners",
  words: "Words:",
  seeAd: "See advertisement",
  getNewWords: "Get {{words}} new words",
  yes: "Yes",
  cancel: "Cancel",
  adLoadingError: "Error with loading advertisement. Try again later.",
  claimReward: "Claim reward!",
  congratulations: "Congratulations",
};

export type LocalizationKeys = typeof en;

export const es = {
  noUser: "No se pudo encontrar al usuario",
  badPassword: "La contraseña es incorrecta",
  userExists: "Este usuario ya existe",
  badEmail: "El correo no es válido",
  emailPlaceholder: "Correo electrónico",
  passwordPlaceholder: "Contraseña",
  confirmPasswordPlaceholder: "Confirmar contraseña",
  somethingWrong: "Algo anda mal. Vuelve a intentarlo más tarde.",
  logIn: "Iniciar sesión",
  logInBenefit: "Para obtener más palabras y guardarlas en su colección",
  logInButton: "Registrarse",
  orUse: "o usar",
  logInWithFacebook: "Iniciar sesión con Facebook",
  noAccount: "¿No tienes una cuenta?",
  signUp: "Regístrate",
  haveAccount: "¿Ya tienes una cuenta?",
  signIn: "Registrarse",
  agreeWith: "estoy de acuerdo con",
  privacyPolicy: "política de privacidad",
  forgotPassword: "¿Se te olvidó tu contraseña?",
  forgotPasswordDisclaimer: "Proporcione el correo electrónico para su cuenta",
  emailHasBeenSended:
    "El mensaje ha sido enviado a la dirección de correo electrónico indicada.",
  loggedInWithServices:
    "Cuenta con registros de correo electrónico dados de diferentes fuentes",
  send: "Enviar",
  helloUser: "¡Hola, {{user}}!",
  changeLanguage: "Idioma",
  logOut: "Cerrar sesión",
  newGame: "Nuevo juego",
  resumeGame: "Reanudar juego",
  categories: "Categorías",
  showBought: "espectáculo comprado",
  buyCategory: "Categoría de compra",
  randomWord: "Palabra aleatoria",
  youHaveNewWords: "¡Tienes nuevas palabras!",
  saveCategory: "Guardar categoría",
  super: "súper",
  getWords: "Obtener nuevas palabras",
  howToPlay: "¿Cómo jugar?",
  howToPlay1: "¡Reúne a un grupo de amigos, configura el juego y diviértete!",
  howToPlay2: "Mostrar palabra dibujada y no decir nada",
  howToPlay3:
    "Si te quedas sin palabras, ¡puedes conseguir nuevas y aumentar tu colección!",
  reset: "Reiniciar",
  teamsAmount: "Numero de equipos",
  players: "Jugadores",
  roundTime: "Tiempo redondo",
  whenWin: "Puntos",
  countType: "Tipo",
  rollTeams: "Jugadores aleatorios",
  rollTeamsAgain: "Al azar otra vez",
  startGame: "Empezar juego",
  startNewGame: "Empieza un juego nuevo",
  numberOfWords: "Cantidad de palabras elegidas",
  roll: "Rodar",
  free: "gratis",
  randomFreeWords: "Palabras libres",
  dontKnowWords: "Será mejor si no conoces las palabras.",
  wantToSee: "quiero ver",
  thanks: "Gracias",
  gameSettings: "Configuraciones de juego",
  onePerRound: "Punto por ronda",
  asManyPerRound: "El mayor número posible",
  nameOrNick: "Nombre o nick",
  clearHistory: "historia clara",
  selectCategories: "Seleccionar categorías",
  selectedWords: "Palabras seleccionadas",
  letsPlay: "¡Juguemos el juego!",
  red: "Equipo rojo",
  green: "Equipo verde",
  orange: "Equipo naranja",
  blue: "Equipo azul",
  violet: "Equipo violeta",
  yellow: "Equipo amarillo",
  round: "Redondo:",
  category: "Categoría:",
  replaceWordOnce: "Reemplazar la palabra una vez",
  correct: "Correcto",
  winner: "Ganador",
  winners: "Ganadores",
  words: "Palabras:",
  seeAd: "Ver publicidad",
  getNewWords: "Obtenga {{words}} palabras nuevas",
  yes: "si",
  cancel: "Cancelar",
  adLoadingError: "Error al cargar publicidad. Inténtelo de nuevo más tarde.",
  claimReward: "¡Reclamar recompensa!",
  congratulations: "Felicidades",
};

export const de = {
  noUser: "Benutzer konnte nicht gefunden werden",
  badPassword: "Passwort ist falsch",
  userExists: "Dieser Benutzer existiert bereits",
  badEmail: "Email ist ungültig",
  emailPlaceholder: "Email",
  passwordPlaceholder: "Passwort",
  confirmPasswordPlaceholder: "Passwort bestätigen",
  somethingWrong:
    "Irgendwas stimmt nicht, bitte versuchen Sie es später noch einmal",
  logIn: "Einloggen",
  logInBenefit:
    "Um mehr Wörter zu erhalten und sie in Ihrer Sammlung zu speichern",
  logInButton: "Anmelden",
  orUse: "oder verwenden",
  logInWithFacebook: "Mit Facebook einloggen",
  noAccount: "Sie haben noch keinen Account?",
  signUp: "Anmelden",
  haveAccount: "Sie haben bereits ein Konto?",
  signIn: "Anmelden",
  agreeWith: "Ich bin einverstanden mit",
  privacyPolicy: "Datenschutz-Bestimmungen",
  forgotPassword: "Passwort vergessen?",
  forgotPasswordDisclaimer: "Geben Sie eine E-Mail für Ihr Konto an",
  emailHasBeenSended:
    "Die Nachricht wurde an die angegebene E-Mail-Adresse gesendet",
  loggedInWithServices:
    "Konto mit angegebenen E-Mail-Protokollen aus verschiedenen Quellen",
  send: "Senden",
  helloUser: "Hallo {{user}}!",
  changeLanguage: "Sprache",
  logOut: "Ausloggen",
  newGame: "Neues Spiel",
  resumeGame: "Spiel fortsetzen",
  categories: "Kategorien",
  showBought: "Show gekauft",
  buyCategory: "Kategorie kaufen",
  randomWord: "Zufälliges Wort",
  youHaveNewWords: "Du hast neue Wörter!",
  saveCategory: "Kategorie speichern",
  super: "Super",
  getWords: "Holen Sie sich neue Wörter",
  howToPlay: "Spielanleitung?",
  howToPlay1:
    "Sammeln Sie eine Gruppe von Freunden, richten Sie das Spiel ein und haben Sie Spaß!",
  howToPlay2: "Zeigen Sie gezeichnetes Wort und sagen Sie nichts",
  howToPlay3:
    "Wenn Ihnen die Wörter ausgehen, können Sie neue erhalten und Ihre Sammlung erweitern!",
  reset: "zurücksetzen",
  teamsAmount: "Anzahl der Teams",
  players: "Spieler",
  roundTime: "Runde Zeit",
  whenWin: "Punkte",
  countType: "Art",
  rollTeams: "Zufällige Spieler",
  rollTeamsAgain: "Wieder zufällig",
  startGame: "Spiel starten",
  startNewGame: "Neues Spiel starten",
  numberOfWords: "Anzahl der ausgewählten Wörter",
  roll: "Rollen",
  free: "frei",
  randomFreeWords: "Freie Wörter",
  dontKnowWords: "Es wird besser sein, wenn Sie die Wörter nicht kennen.",
  wantToSee: "Ich möchte sehen",
  thanks: "Vielen Dank",
  gameSettings: "Spieleinstellungen",
  onePerRound: "Punkt pro Runde",
  asManyPerRound: "So viele wie möglich",
  nameOrNick: "Name oder Spitzname",
  clearHistory: "klare Geschichte",
  selectCategories: "Wählen Sie Kategorien aus",
  selectedWords: "Ausgewählte Wörter",
  letsPlay: "Lass uns das Spiel spielen!",
  red: "Rotes Team",
  green: "Grünes Team",
  orange: "Orange Team",
  blue: "Blaues Team",
  violet: "Violettes Team",
  yellow: "Gelbes Team",
  round: "Runden:",
  category: "Kategorie:",
  replaceWordOnce: "Ersetzen Sie das Wort einmal",
  correct: "Richtig",
  winner: "Gewinner",
  winners: "Gewinner",
  words: "Wörter:",
  seeAd: "Siehe Werbung",
  getNewWords: "Holen Sie sich {{words}} neue Wörter",
  yes: "Ja",
  cancel: "Stornieren",
  adLoadingError:
    "Fehler beim Laden der Werbung. Versuchen Sie es später noch einmal.",
  claimReward: "Belohnung beanspruchen!",
  congratulations: "Herzliche Glückwünsche",
};

export const ru = {
  noUser: "Не удалось найти пользователя",
  badPassword: "Пароль неверный",
  userExists: "Это пользователь уже существует",
  badEmail: "Email не является допустимым",
  emailPlaceholder: "Эл. почта",
  passwordPlaceholder: "пароль",
  confirmPasswordPlaceholder: "Подтвердить Пароль",
  somethingWrong: "Что-то не так, попробуйте позже",
  logIn: "Авторизоваться",
  logInBenefit: "Чтобы получить больше слов и сохранить их в своей коллекции",
  logInButton: "войти в систему",
  orUse: "или используйте",
  logInWithFacebook: "Войти с Facebook",
  noAccount: "Нет учетной записи?",
  signUp: "зарегистрироваться",
  haveAccount: "Уже есть аккаунт?",
  signIn: "войти в систему",
  agreeWith: "я согласен с",
  privacyPolicy: "политика конфиденциальности",
  forgotPassword: "Забыли пароль?",
  forgotPasswordDisclaimer:
    "Укажите электронную почту для вашей учетной записи",
  emailHasBeenSended:
    "Сообщение было отправлено на указанный адрес электронной почты",
  loggedInWithServices:
    "Учетная запись с данными журналами электронной почты из разных источников",
  send: "послать",
  helloUser: "Привет, {{user}}!",
  changeLanguage: "Язык",
  logOut: "Выйти",
  newGame: "Новая игра",
  resumeGame: "Продолжить игру",
  categories: "Категории",
  showBought: "показать куплено",
  buyCategory: "Купить Категория",
  randomWord: "Случайное слово",
  youHaveNewWords: "У тебя есть новые слова!",
  saveCategory: "Сохранить категорию",
  super: "Супер",
  getWords: "Получите новые слова",
  howToPlay: "Как играть?",
  howToPlay1:
    "Соберите группу друзей, настройте игру и получайте удовольствие!",
  howToPlay2: "Показать нарисованное слово и ничего не сказать",
  howToPlay3:
    "Если у Вас кончатся слова, Вы можете получить новые и пополнить свою коллекцию!",
  reset: "сброс",
  teamsAmount: "Количество команд",
  players: "Игроки",
  roundTime: "Время раунда",
  whenWin: "Точки",
  countType: "Тип",
  rollTeams: "Случайные игроки",
  rollTeamsAgain: "Снова случайный",
  startGame: "Начать игру",
  startNewGame: "Начать новую игру",
  numberOfWords: "Количество выбранных слов",
  roll: "Рулон",
  free: "бесплатно",
  randomFreeWords: "Свободные слова",
  dontKnowWords: "Будет лучше, если Ты не знаешь слов.",
  wantToSee: "Я хочу увидеть",
  thanks: "Спасибо",
  gameSettings: "Настройки игры",
  onePerRound: "Очков за раунд",
  asManyPerRound: "Как можно больше",
  nameOrNick: "Имя или ник",
  clearHistory: "чистая история",
  selectCategories: "Выбрать категории",
  selectedWords: "Выбранные слова",
  letsPlay: "Поиграем в игру!",
  red: "Красная команда",
  green: "Зеленая команда",
  orange: "Оранжевая команда",
  blue: "Синяя команда",
  violet: "Фиолетовая команда",
  yellow: "Желтая команда",
  round: "Круглый:",
  category: "Категория:",
  replaceWordOnce: "Замени слово один раз",
  correct: "Верный",
  winner: "Победитель",
  winners: "Победители",
  words: "Слова:",
  seeAd: "Посмотреть рекламу",
  getNewWords: "Получите {{words}} новых слов",
  yes: "да",
  cancel: "Отмена",
  adLoadingError: "Ошибка загрузки рекламы. Попробуйте позже.",
  claimReward: "Награда претензии!",
  congratulations: "Поздравления",
};

export const languages = ["pl", "en", "ru", "de", "es"];
export const fullLanguages: FullLanguage[] = [
  { full: "English", id: "en", flag: "gb,us" },
  { full: "Polski", id: "pl", flag: "pl" },
  { full: "Pусский", id: "ru", flag: "ru" },
  { full: "Deutsh", id: "de", flag: "ger" },
  { full: "Español", id: "es", flag: "es" },
];
